### ISSUE TITLE
fix dynamic compilation on windows/msys

### ISSUE THREAD

**Issue by rondiplomatico** [OpenCMISS-Dependencies/cellml#11]
currently disabling DYNAMIC_COMPILATION for MSYS environment
maybe use [this](https://github.com/dlfcn-win32/dlfcn-win32/blob/master/CMakeLists.txt)?

**Comment by nickerso** [comment]
See also #13.

**Comment by nickerso** [comment]
#15 introduced ability to use CSim which removes the need for dynamic compilation - particularly on platforms which are not likely to have gcc handy. Considering this closed for now, reopen if a use-case for dynamic compilation on windows emerges which is not resolved through the use of CSim.
