### ISSUE TITLE
Migrate to CSim

### ISSUE THREAD

**Issue by nickerso** [OpenCMISS-Dependencies/cellml#13]
It would be useful in terms of maintenance and functionality to migrate this code over to https://github.com/nickerso/csim-v2. But this will require the addition of LLVM+Clang to the list of OpenCMISS dependencies and thus requires a fair amount of work. Including binary builds of CSim-v2 might be a good way to avoid this on platforms that may not provide system versions of LLVM+Clang with all the required libraries.

**Comment by nickerso** [comment]
So turns out LLVM+Clang and CSim are already (unused) components in the CMake build system. I'll take a look at getting them updated and building and then migrate the internals of cellml to use CSim and remove the need for users to have their own gcc installed.

**Comment by rondiplomatico** [comment]
it sure would'nt hurt if the cellml package could still work without csim/llvm if a gcc was found? this could be a CMake flag "CELLML_USE_GCC"? that could be used whenever people cant get llvm to work..

**Comment by nickerso** [comment]
closed by #15.
